# Generated by Django 2.2.5 on 2021-12-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20211213_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='type',
            field=models.CharField(choices=[('V', 'Voting'), ('BV', 'BinaryVoting'), ('MV', 'MultipleVoting'), ('SV', 'ScoreVoting')], default='V', max_length=2),
        ),
    ]
