# Generated by Django 2.0 on 2021-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('auto_msg', models.BooleanField(default=False)),
            ],
        ),
    ]
