# Generated by Django 2.2.5 on 2022-01-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('auto_msg', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telegram user',
            },
        ),
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.BigIntegerField()),
                ('voting_type', models.CharField(default='V', max_length=30)),
                ('graphs_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('voting_id', 'voting_type')},
            },
        ),
    ]
