# Generated by Django 2.2.5 on 2022-01-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': 'Telegram user'},
        ),
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.BigIntegerField()),
                ('voting_type', models.CharField(default='V', max_length=30)),
                ('graphs_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('voting_id', 'voting_type')},
            },
        ),
    ]
