# Generated by Django 2.0 on 2021-12-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': 'Telegram user'},
        ),
    ]
