# Generated by Django 2.2.5 on 2021-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryvoting',
            name='type',
            field=models.CharField(choices=[('BV', 'BinaryVoting')], default='BV', max_length=2),
        ),
    ]
