name: DeployToHerokuServer

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "decide-admin-test"
          heroku_email: "esoj.nieves@gmail.com"

    - name: Successful Message
      run: echo Successfully Deployed!!
